name: pre-release

on:
  workflow_run:
    workflows: ["build-document"]
    branches: [master]
    types:
      - completed
    paths-ignore:
      - '**/README.md'

  workflow_dispatch:
  
jobs:
  create-pre-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: projeto-pesquisa-ufscar.tex
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: "*.pdf"